CREATE TABLE Inventory(
	ID		VARCHAR(20) NOT NULL,
	Quantity		INT,
	[Description]	VARCHAR(20),
	VendorID	INT,
	VendorPN	VARCHAR(30),
	CONSTRAINT PK_Inventory PRIMARY KEY(ID)
);
GO

CREATE TABLE [Order](
	ID			INT NOT NULL IDENTITY,
	CustomerID		INT,
	InventoryID		VARCHAR(20),
	OrderQuantity	INT,
	OrderDate		DATE,
	Shipped			BIT DEFAULT(0),
	CONSTRAINT PK_Order PRIMARY KEY(ID)
);
GO

CREATE TABLE Customer(
	ID		INT NOT NULL IDENTITY,
	CustomerCompany	VARCHAR(30),
	CustomerName	VARCHAR(40),
	CustomerAddress	VARCHAR(100),
	CONSTRAINT PK_Customer PRIMARY KEY(ID)
);
GO

CREATE TABLE Vendor(
	ID		INT NOT NULL IDENTITY,
	VendorName		VARCHAR(40),
	VendorAddress	VARCHAR(100),
	CONSTRAINT PK_Vendor PRIMARY KEY(ID)
);
GO

CREATE TABLE ProductSN(
	ID		INT NOT NULL IDENTITY,
	InventoryID		VARCHAR(20),
	CONSTRAINT PK_ProductSN PRIMARY KEY(ID)
);
GO

CREATE TABLE MonicoSN(
	ID INT NOT NULL IDENTITY,
	MonicoSN		VARCHAR(10) NOT NULL,
	MonicoSIM		VARCHAR(17) NOT NULL,
	ProductSNID		INT,
	CONSTRAINT PK_MonicoSN PRIMARY KEY(ID),
);
GO

CREATE TABLE IDP680SN(
	ID INT NOT NULL IDENTITY,
	IDP680SN	VARCHAR(15) NOT NULL,
	ProductSNID	INT,
	CONSTRAINT PK_IDP680SN PRIMARY KEY(ID)
);
GO

CREATE TABLE IDP782SN(
	ID INT NOT NULL IDENTITY,
	IDP782SN	VARCHAR(15) NOT NULL,
	IDP782SIM	INT NOT NULL IDENTITY,
	ProductSNID INT,
	CONSTRAINT PK_IDP782SN PRIMARY KEY(ID)
);
GO

ALTER TABLE Inventory ADD CONSTRAINT FK_Inventory_Vendor FOREIGN KEY(VendorID) REFERENCES Vendor(ID);
ALTER TABLE [Order] ADD CONSTRAINT FK_Order_Inventory FOREIGN KEY(InventoryID) REFERENCES Inventory(ID);
ALTER TABLE Customer ADD CONSTRAINT FK_Order_Customer FOREIGN KEY(CustomerID) REFERENCES Customer(ID);
ALTER TABLE ProductSN ADD CONSTRAINT FK_ProductSN_Inventory FOREIGN KEY(InventoryID) REFERENCES Inventory(ID);
ALTER TABLE MonicoSN ADD CONSTRAINT FK_MonicoSN_ProductSN FOREIGN KEY(ProductSNID) REFERENCES ProductSN(ID);
ALTER TABLE IDP680SN ADD CONSTRAINT FK_IDP680SN_ProductSN FOREIGN KEY(ProductSNID) REFERENCES ProductSN(ID);
ALTER TABLE IDP782SN ADD CONSTRAINT FK_MonicoSN_ProductSN FOREIGN KEY(ProductSNID) REFERENCES ProductSN(ID);