CREATE TABLE Inventory(
	InventoryID		VARCHAR(20) NOT NULL IDENTITY,
	Quantity		INT,
	[Description]	VARCHAR(20),
	ManufactureID	INT,
	ManufacturePN	VARCHAR(30),
	CONSTRAINT PK_Inventory PRIMARY KEY(InventoryID)
);
GO

CREATE TABLE [Order](
	OrderID			INT NOT NULL IDENTITY,
	CustomerID		INT,
	InventoryID		VARCHAR(20),
	OrderQuantity	INT,
	OrderDate		DATE,
	Shipped			BIT DEFAULT(0),
	CONSTRAINT PK_Order PRIMARY KEY(OrderID)
);
GO

CREATE TABLE Customer(
	CustomerID		INT NOT NULL IDENTITY,
	CustomerCompany	VARCHAR(30),
	CustomerName	VARCHAR(40),
	CustomerAddress	VARCHAR(100),
	CONSTRAINT PK_Customer PRIMARY KEY(CustomerID)
);
GO

CREATE TABLE Manufacture(
	ManufactureID		INT NOT NULL IDENTITY,
	ManufactureName		VARCHAR(40),
	ManufactureAddress	VARCHAR(100),
	CONSTRAINT PK_Manufacture PRIMARY KEY(ManufactureID)
);
GO

CREATE TABLE ProductSN(
	ProductSNID		INT NOT NULL IDENTITY,
	InventoryID		VARCHAR(20),
	CONSTRAINT PK_ProductSN PRIMARY KEY(ProductSNID)
);
GO

CREATE TABLE MonicoSN(
	MonicoSN		VARCHAR(10) NOT NULL IDENTITY,
	MonicoSIM		VARCHAR(17) NOT NULL IDENTITY,
	ProductSNID		INT,
	CONSTRAINT PK_MonicoSN PRIMARY KEY(MonicoSN),
	CONSTRAINT PK_MonicoSIM PRIMARY KEY(MonicoSIM)
);
GO

CREATE TABLE IDP680SN(
	IDP680SN	VARCHAR(15) NOT NULL IDENTITY,
	ProductSNID	INT,
	CONSTRAINT PK_IDP680SN PRIMARY KEY(IDP680SN)
);
GO

CREATE TABLE IDP782SN(
	IDP782SN	VARCHAR(15) NOT NULL IDENTITY,
	IDP782SIM	INT NOT NULL IDENTITY,
	ProductSNID INT,
	CONSTRAINT PK_IDP782SN PRIMARY KEY(IDP782SN),
	CONSTRAINT PK_IDP782SIM PRIMARY KEY(IDP782SIM)
);
GO